[workspace]
members = [
    "util/data",
    "util/tracer",
    "util/tracer_macros",
    "util/lsp",
    "lang/syntax",
    "lang/parser",
    "lang/lowering",
    "lang/printer",
    "lang/core",
    "lang/source",
    "web/crates/browser",
    "app",
    "test/test-runner",
]
default-members = ["app"]
