[package]
name = "app"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "xfunc"
path = "src/main.rs"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# cli
clap = { version = "3", features = ["derive"] }
reedline = "0.10"
termsize = "0.1"
# fancy error messages
miette = { version = "5", features = ["fancy"] }
thiserror = "1"
# workspace members
source = { path = "../lang/source" }
core = { path = "../lang/core" }
syntax = { path = "../lang/syntax" }
parser = { path = "../lang/parser" }
lowering = { path = "../lang/lowering" }
printer = { path = "../lang/printer" }
