[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
# cli
clap = { version = "3", features = ["derive"] }
reedline = "0.10"
termsize = "0.1"
# workspace members
core = { path = "../lang/core" }
syntax = { path = "../lang/syntax" }
parser = { path = "../lang/parser" }
lowering = { path = "../lang/lowering" }
printer = { path = "../lang/printer" }
