[package]
name = "app"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "xfunc"
path = "src/main.rs"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# cli
clap = { version = "4", features = ["derive"] }
termsize = "0.1"
# fancy error messages
miette = { version = "5", features = ["fancy"] }
thiserror = "1"
# lsp
futures = "0.3"
tokio = { version = "1", features = ["full"] }
tower-lsp = { version = "0.17" }
# workspace members
source = { path = "../lang/source" }
core = { path = "../lang/core" }
syntax = { path = "../lang/syntax" }
printer = { path = "../lang/printer" }
lsp-server = { path = "../util/lsp" }