[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
# workspace members
data = { path = "../../util/data" }
tracer = { path = "../../util/tracer" }
syntax = { path = "../syntax" }
printer = { path = "../printer" }
