[package]
name = "syntax"
version = "0.1.0"
edition = "2021"

[dependencies]
# serde
serde = { version = "1", features = ["rc"], optional = true }
serde_derive = { version = "1", optional = true }
# source code locations
codespan = "0.11"
# ignoring fields when deriving traits (e.g. Eq, Hash)
derivative = "2"
# big integers
num-bigint = "0.4"
# lazy static
lazy_static = "1.4.0"
# workspace members
data = { path = "../../util/data" }
console = { path = "../../util/console" }

[features]
default = ["use-serde"]
use-serde = ["serde", "serde_derive"]
