name: Deploy Pages
on: [push]
# on:
#   push: { branches: [main] }
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: wasm32-unknown-unknown
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v2
      - run: |
          mkdir -p gh-pages
      - run: |
          (cd web && make deps && make build)
          cp -r web/packages/app/dist gh-pages/editor
      - run: |
          cargo doc --no-deps --document-private-items
          cp -r target/doc gh-pages/docs
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: gh-pages
