---
name: Lint Code Base

on: [push, pull_request]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          # JSCPD is disabled because it falsely flags duplicated Rust generic parameter definitions
          VALIDATE_JSCPD: false
          # We use eslint instead of the linter named "standard"
          VALIDATE_JAVASCRIPT_STANDARD: false
          # We use prettier rather than ts-standard
          TYPESCRIPT_DEFAULT_STYLE: prettier
          # We use a slightly different stylelint version/setup
          VALIDATE_CSS: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
